import { combineReducers } from "redux";

import checkSymptomReducer from "./checkSymptomReducer";

const initialstate = {
    lan: 'np',
    municipalities : [
        "Province 1, Taplejung, Aatharai Tribeni",
        "Province 1, Taplejung, Maiwakhola",
        "Province 1, Taplejung, Meringden",
        "Province 1, Taplejung, Mikwakhola",
        "Province 1, Taplejung, Phaktanlung",
        "Province 1, Taplejung, Phungling",
        "Province 1, Taplejung, Sidingba",
        "Province 1, Taplejung, Sirijanga",
        "Province 1, Taplejung, Yangwarak",
        "Province 1, Panchthar, Falelung",
        "Province 1, Panchthar, Falgunanda",
        "Province 1, Panchthar, Hilihan",
        "Province 1, Panchthar, Kummayak",
        "Province 1, Panchthar, Miklajung",
        "Province 1, Panchthar, Phidim",
        "Province 1, Panchthar, Tumbewa",
        "Province 1, Panchthar, Yangbarak",
        "Province 1, Ilam, Chulachuli",
        "Province 1, Ilam, Deumai",
        "Province 1, Ilam, Fakfokathum",
        "Province 1, Ilam, Illam",
        "Province 1, Ilam, Mai Jogmai",
        "Province 1, Ilam, Mai",
        "Province 1, Ilam, Mangsebung",
        "Province 1, Ilam, Rong",
        "Province 1, Ilam, Sandakpur",
        "Province 1, Ilam, Suryodaya",
        "Province 1, Jhapa, Arjundhara",
        "Province 1, Jhapa, Barhadashi",
        "Province 1, Jhapa, Bhadrapur",
        "Province 1, Jhapa, Birtamod",
        "Province 1, Jhapa, Buddhashanti",
        "Province 1, Jhapa, Damak",
        "Province 1, Jhapa, Gauradaha",
        "Province 1, Jhapa, Gauriganj",
        "Province 1, Jhapa, Haldibari",
        "Province 1, Jhapa, Jhapa",
        "Province 1, Jhapa, Kachanakawal",
        "Province 1, Jhapa, Kamal",
        "Province 1, Jhapa, Kankai",
        "Province 1, Jhapa, Mechinagar",
        "Province 1, Jhapa, Shivasatakshi",
        "Province 1, Morang, Belbari",
        "Province 1, Morang, Biratnagar",
        "Province 1, Morang, Budhiganga",
        "Province 1, Morang, Dhanapalthan",
        "Province 1, Morang, Gramthan",
        "Province 1, Morang, Jahada",
        "Province 1, Morang, Kanepokhari",
        "Province 1, Morang, Katahari",
        "Province 1, Morang, Kerabari",
        "Province 1, Morang, Letang",
        "Province 1, Morang, Miklajung",
        "Province 1, Morang, Pathari Shanishchare",
        "Province 1, Morang, Rangeli",
        "Province 1, Morang, Ratuwamai",
        "Province 1, Morang, Sundarharaicha",
        "Province 1, Morang, Sunwarshi",
        "Province 1, Morang, Urlabari",
        "Province 1, Sunsari, Baraha",
        "Province 1, Sunsari, Barju",
        "Province 1, Sunsari, Bhokraha",
        "Province 1, Sunsari, Dewangunj",
        "Province 1, Sunsari, Dharan",
        "Province 1, Sunsari, Duhabi",
        "Province 1, Sunsari, Gadhi",
        "Province 1, Sunsari, Harinagara",
        "Province 1, Sunsari, Inaruwa",
        "Province 1, Sunsari, Itahari",
        "Province 1, Sunsari, Koshi",
        "Province 1, Sunsari, Ramdhuni",
        "Province 1, Dhankuta, Chaubise",
        "Province 1, Dhankuta, Chhathar Jorpati",
        "Province 1, Dhankuta, Dhankuta",
        "Province 1, Dhankuta, Khalsa Chhintang Sahidbhumi",
        "Province 1, Dhankuta, Mahalaxmi",
        "Province 1, Dhankuta, Pakhribas",
        "Province 1, Dhankuta, Sangurigadhi",
        "Province 1, Terhathum, Aatharai",
        "Province 1, Terhathum, Chhathar",
        "Province 1, Terhathum, Laligurans",
        "Province 1, Terhathum, Menchhayayem",
        "Province 1, Terhathum, Myanglung",
        "Province 1, Terhathum, Phedap",
        "Province 1, Sankhuwasabha, Bhotkhola",
        "Province 1, Sankhuwasabha, Chainapur",
        "Province 1, Sankhuwasabha, Chichila",
        "Province 1, Sankhuwasabha, Dharmadevi",
        "Province 1, Sankhuwasabha, Khandabari",
        "Province 1, Sankhuwasabha, Madi",
        "Province 1, Sankhuwasabha, Makalu",
        "Province 1, Sankhuwasabha, Panchakhapan",
        "Province 1, Sankhuwasabha, Sabhapokhari",
        "Province 1, Sankhuwasabha, Silichong",
        "Province 1, Bhojpur, Aamchowk",
        "Province 1, Bhojpur, Arun",
        "Province 1, Bhojpur, Bhojpur",
        "Province 1, Bhojpur, Hatuwagadhi",
        "Province 1, Bhojpur, Pauwa Dunma",
        "Province 1, Bhojpur, Ramprasad Rai",
        "Province 1, Bhojpur, Salpa Silichho",
        "Province 1, Bhojpur, Shadananda",
        "Province 1, Bhojpur, Tyamke Maiyum",
        "Province 1, Solukhumbu, Dhudha Koushika",
        "Province 1, Solukhumbu, Dhudhakoshi",
        "Province 1, Solukhumbu, Khumbu Pasanglhamu",
        "Province 1, Solukhumbu, Likhu Pike",
        "Province 1, Solukhumbu, Mahakulung",
        "Province 1, Solukhumbu, Necha Salyan",
        "Province 1, Solukhumbu, Solu Dhudhakunda",
        "Province 1, Solukhumbu, Sotang",
        "Province 1, Okhaldhunga, Champadevi",
        "Province 1, Okhaldhunga, Chishankhu Gadhi",
        "Province 1, Okhaldhunga, Khiji Demba",
        "Province 1, Okhaldhunga, Likhu",
        "Province 1, Okhaldhunga, Manebhanjyang",
        "Province 1, Okhaldhunga, Molung",
        "Province 1, Okhaldhunga, Siddhicharan",
        "Province 1, Okhaldhunga, Sunkoshi",
        "Province 1, Khotang, Aiselukharka",
        "Province 1, Khotang, Baraha Pokhari",
        "Province 1, Khotang, Diprung",
        "Province 1, Khotang, Halesi Tuwachung",
        "Province 1, Khotang, Jante Dhunga",
        "Province 1, Khotang, Kepilasgadhi",
        "Province 1, Khotang, Khotehang",
        "Province 1, Khotang, Lamidanda",
        "Province 1, Khotang, Rupakot Majhuwagadhi",
        "Province 1, Khotang, Sakela",
        "Province 1, Udayapur, Belaka",
        "Province 1, Udayapur, Chaudandigadhi",
        "Province 1, Udayapur, Katari",
        "Province 1, Udayapur, Rautamai",
        "Province 1, Udayapur, Sunkoshi",
        "Province 1, Udayapur, Tapli",
        "Province 1, Udayapur, Triyuga",
        "Province 1, Udayapur, Udayapurgadhi",
        "Province 2, Saptari, Agmisair Krishna Sabaran",
        "Province 2, Saptari, Balan-Bihul",
        "Province 2, Saptari, Belhi Chapena",
        "Province 2, Saptari, Bishnupur",
        "Province 2, Saptari, Bode Barsain",
        "Province 2, Saptari, Chhinnamasta",
        "Province 2, Saptari, Dakneshwori",
        "Province 2, Saptari, Hanumannagar Kankalini",
        "Province 2, Saptari, Kanchanrup",
        "Province 2, Saptari, Khadak",
        "Province 2, Saptari, Mahadewa",
        "Province 2, Saptari, Rajbiraj",
        "Province 2, Saptari, Rupani",
        "Province 2, Saptari, Saptakoshi",
        "Province 2, Saptari, Shambhunath",
        "Province 2, Saptari, Surunga",
        "Province 2, Saptari, Tilathi Koiladi",
        "Province 2, Saptari, Tirahut",
        "Province 2, Siraha, Arnama",
        "Province 2, Siraha, Aurahi",
        "Province 2, Siraha, Bariyarpatti",
        "Province 2, Siraha, Bhagawanpur",
        "Province 2, Siraha, Bishnupur",
        "Province 2, Siraha, Dhangadhimai",
        "Province 2, Siraha, Golbazar",
        "Province 2, Siraha, Kalyanpur",
        "Province 2, Siraha, Karjanha",
        "Province 2, Siraha, Lahan",
        "Province 2, Siraha, Laxmipur Patari",
        "Province 2, Siraha, Mirchaiya",
        "Province 2, Siraha, Naraha",
        "Province 2, Siraha, Nawarajpur",
        "Province 2, Siraha, Sakhuwa Nankarkatti",
        "Province 2, Siraha, Siraha",
        "Province 2, Siraha, Sukhipur",
        "Province 2, Dhanusa, Aurahi",
        "Province 2, Dhanusa, Bateshwor",
        "Province 2, Dhanusa, Bideha",
        "Province 2, Dhanusa, Chhireshwornath",
        "Province 2, Dhanusa, Dhanauji",
        "Province 2, Dhanusa, Dhanushadham",
        "Province 2, Dhanusa, Ganeshman Charnath",
        "Province 2, Dhanusa, Hansapur",
        "Province 2, Dhanusa, Janak Nandini",
        "Province 2, Dhanusa, Janakpur",
        "Province 2, Dhanusa, Kamala",
        "Province 2, Dhanusa, Laxminiya",
        "Province 2, Dhanusa, Mithila Bihari",
        "Province 2, Dhanusa, Mithila",
        "Province 2, Dhanusa, Mukhiyapatti Musaharmiya",
        "Province 2, Dhanusa, Nagarain",
        "Province 2, Dhanusa, Sabaila",
        "Province 2, Dhanusa, Shahidnagar",
        "Province 2, Mahottari, Aurahi",
        "Province 2, Mahottari, Balawa",
        "Province 2, Mahottari, Bardibas",
        "Province 2, Mahottari, Bhangaha",
        "Province 2, Mahottari, Ekadara",
        "Province 2, Mahottari, Gaushala",
        "Province 2, Mahottari, Jaleshwor",
        "Province 2, Mahottari, Loharpatti",
        "Province 2, Mahottari, Mahottari",
        "Province 2, Mahottari, Manara Shisawa",
        "Province 2, Mahottari, Matihani",
        "Province 2, Mahottari, Pipara",
        "Province 2, Mahottari, Ram Gopalpur",
        "Province 2, Mahottari, Samsi",
        "Province 2, Mahottari, Sonama",
        "Province 2, Sarlahi, Bagmati",
        "Province 2, Sarlahi, Balara",
        "Province 2, Sarlahi, Barahathawa",
        "Province 2, Sarlahi, Basbariya",
        "Province 2, Sarlahi, Bishnu",
        "Province 2, Sarlahi, Brahmapuri",
        "Province 2, Sarlahi, Chakraghatta",
        "Province 2, Sarlahi, Chandranagar",
        "Province 2, Sarlahi, Dhanakaul",
        "Province 2, Sarlahi, Godaita",
        "Province 2, Sarlahi, Haripur",
        "Province 2, Sarlahi, Haripurwa",
        "Province 2, Sarlahi, Hariwan",
        "Province 2, Sarlahi, Ishworpur",
        "Province 2, Sarlahi, Kabilashi",
        "Province 2, Sarlahi, Kaudena",
        "Province 2, Sarlahi, Lalbandi",
        "Province 2, Sarlahi, Malangawa",
        "Province 2, Sarlahi, Parsa",
        "Province 2, Sarlahi, Ramnagar",
        "Province 2, Rautahat, Boudhimai",
        "Province 2, Rautahat, Brindaban",
        "Province 2, Rautahat, Chandrapur",
        "Province 2, Rautahat, Dewahi Gonahi",
        "Province 2, Rautahat, Durga Bhagawati",
        "Province 2, Rautahat, Gadhimai",
        "Province 2, Rautahat, Garuda",
        "Province 2, Rautahat, Gaur",
        "Province 2, Rautahat, Gujara",
        "Province 2, Rautahat, Ishanath",
        "Province 2, Rautahat, Katahariya",
        "Province 2, Rautahat, Madhav Narayan",
        "Province 2, Rautahat, Maulapur",
        "Province 2, Rautahat, Paroha",
        "Province 2, Rautahat, Phatuwa Bijayapur",
        "Province 2, Rautahat, Rajdevi",
        "Province 2, Rautahat, Rajpur",
        "Province 2, Rautahat, Yamunamai",
        "Province 2, Bara, Aadarsha Kotwal",
        "Province 2, Bara, Baragadhi",
        "Province 2, Bara, Bishrampur",
        "Province 2, Bara, Devtal",
        "Province 2, Bara, Jitpur Simara",
        "Province 2, Bara, Kalaiya",
        "Province 2, Bara, Karaiyamai",
        "Province 2, Bara, Kolhabi",
        "Province 2, Bara, Mahagadhimai",
        "Province 2, Bara, Nijagadh",
        "Province 2, Bara, Pacharauta",
        "Province 2, Bara, Parawanipur",
        "Province 2, Bara, Pheta",
        "Province 2, Bara, Prasauni",
        "Province 2, Bara, Simroungadh",
        "Province 2, Bara, Subarna",
        "Province 2, Parsa, Bahudarmai",
        "Province 2, Parsa, Bindabasini",
        "Province 2, Parsa, Birgunj",
        "Province 2, Parsa, Chhipaharmai",
        "Province 2, Parsa, Dhobini",
        "Province 2, Parsa, Jagarnathpur",
        "Province 2, Parsa, Jirabhawani",
        "Province 2, Parsa, Kalikamai",
        "Province 2, Parsa, Pakaha Mainpur",
        "Province 2, Parsa, Parsagadhi",
        "Province 2, Parsa, Paterwa Sugauli",
        "Province 2, Parsa, Pokhariya",
        "Province 2, Parsa, Sakhuwa Prasauni",
        "Province 2, Parsa, Thori",
        "Province 3, Sindhuli, Dudhouli",
        "Province 3, Sindhuli, Ghyanglekha",
        "Province 3, Sindhuli, Golanjor",
        "Province 3, Sindhuli, Hariharpurgaghi",
        "Province 3, Sindhuli, Kamalamai",
        "Province 3, Sindhuli, Marin",
        "Province 3, Sindhuli, Phikkal",
        "Province 3, Sindhuli, Sunkoshi",
        "Province 3, Sindhuli, Tinpatan",
        "Province 3, Ramechhap, Doramba",
        "Province 3, Ramechhap, Gokulganga",
        "Province 3, Ramechhap, Khandadevi",
        "Province 3, Ramechhap, Likhu",
        "Province 3, Ramechhap, Manthali ",
        "Province 3, Ramechhap, Ramechhap",
        "Province 3, Ramechhap, Sunapati",
        "Province 3, Ramechhap, Umakunda",
        "Province 3, Dolakha, Baitedhar",
        "Province 3, Dolakha, Bhimeshwor",
        "Province 3, Dolakha, Bigu",
        "Province 3, Dolakha, Gaurishankar",
        "Province 3, Dolakha, Jiri",
        "Province 3, Dolakha, Kalinchowk",
        "Province 3, Dolakha, Melung",
        "Province 3, Dolakha, Shailung",
        "Province 3, Dolakha, Tamakoshi",
        "Province 3, Sindhupalchok, Bahrabise",
        "Province 3, Sindhupalchok, Balephi",
        "Province 3, Sindhupalchok, Bhotekoshi",
        "Province 3, Sindhupalchok, Choutara Sangachowkgadhi",
        "Province 3, Sindhupalchok, Helambu",
        "Province 3, Sindhupalchok, Indrawoti",
        "Province 3, Sindhupalchok, Jugal",
        "Province 3, Sindhupalchok, Lisankhu Pakhar",
        "Province 3, Sindhupalchok, Melanchi",
        "Province 3, Sindhupalchok, Panchpokhari Thangpal",
        "Province 3, Sindhupalchok, Sunkoshi",
        "Province 3, Sindhupalchok, Tripurasundari",
        "Province 3, Kavrepalanchok, Banepa",
        "Province 3, Kavrepalanchok, Bethanchowk",
        "Province 3, Kavrepalanchok, Bhumlu",
        "Province 3, Kavrepalanchok, Chauri Deurali",
        "Province 3, Kavrepalanchok, Dhulikhel",
        "Province 3, Kavrepalanchok, Khanikhola",
        "Province 3, Kavrepalanchok, Mahabharat",
        "Province 3, Kavrepalanchok, Mandan Deupur",
        "Province 3, Kavrepalanchok, Namobuddha",
        "Province 3, Kavrepalanchok, Panauti",
        "Province 3, Kavrepalanchok, Panchkhal",
        "Province 3, Kavrepalanchok, Roshi",
        "Province 3, Kavrepalanchok, Temal",
        "Province 3, Lalitpur, Bagmati",
        "Province 3, Lalitpur, Godawari",
        "Province 3, Lalitpur, Konjyosom",
        "Province 3, Lalitpur, Lalitpur",
        "Province 3, Lalitpur, Mahalaxmi",
        "Province 3, Lalitpur, Mahankal",
        "Province 3, Bhaktapur, Bhaktapur",
        "Province 3, Bhaktapur, Changunarayan",
        "Province 3, Bhaktapur, Madhyapur Thimi",
        "Province 3, Bhaktapur, Suryabinayak",
        "Province 3, Kathmandu, Budhanilkhantha",
        "Province 3, Kathmandu, Chandragiri",
        "Province 3, Kathmandu, Dakshinkali",
        "Province 3, Kathmandu, Gokarneshwor",
        "Province 3, Kathmandu, Kageshwori Manahara",
        "Province 3, Kathmandu, Kathmandu",
        "Province 3, Kathmandu, Kirtipur",
        "Province 3, Kathmandu, Nagarjun",
        "Province 3, Kathmandu, Shankharapur",
        "Province 3, Kathmandu, Tarakeshwor",
        "Province 3, Kathmandu, Tokha",
        "Province 3, Nuwakot, Belkotgadhi",
        "Province 3, Nuwakot, Bidur",
        "Province 3, Nuwakot, Dupcheshwor",
        "Province 3, Nuwakot, Kakani",
        "Province 3, Nuwakot, Kispang",
        "Province 3, Nuwakot, Likhu",
        "Province 3, Nuwakot, Meghang",
        "Province 3, Nuwakot, Panchakanya",
        "Province 3, Nuwakot, Shivapuri",
        "Province 3, Nuwakot, Suryagadhi",
        "Province 3, Nuwakot, Tadi",
        "Province 3, Nuwakot, Tarakeshwor",
        "Province 3, Rasuwa, Gosaikunda",
        "Province 3, Rasuwa, Kalika",
        "Province 3, Rasuwa, Naukunda",
        "Province 3, Rasuwa, Parbatikunda",
        "Province 3, Rasuwa, Uttargaya",
        "Province 3, Dhading, Benighat Rorang",
        "Province 3, Dhading, Dhunibenshi",
        "Province 3, Dhading, Gajuri",
        "Province 3, Dhading, Galchhi",
        "Province 3, Dhading, Ganga Jamuna",
        "Province 3, Dhading, Jwalamukhi",
        "Province 3, Dhading, Khaniyabas",
        "Province 3, Dhading, Netrawati",
        "Province 3, Dhading, Nilkhantha",
        "Province 3, Dhading, Rubi Valley",
        "Province 3, Dhading, Siddhalek",
        "Province 3, Dhading, Thakre",
        "Province 3, Dhading, Tripurasundari",
        "Province 3, Makwanpur, Bagmati",
        "Province 3, Makwanpur, Bakaiya",
        "Province 3, Makwanpur, Bhimphedi",
        "Province 3, Makwanpur, Hetauda",
        "Province 3, Makwanpur, Indrasarowar",
        "Province 3, Makwanpur, Kailash",
        "Province 3, Makwanpur, Makawanpurgadhi",
        "Province 3, Makwanpur, Manahari",
        "Province 3, Makwanpur, Raksirang",
        "Province 3, Makwanpur, Thaha",
        "Province 3, Chitawan, Bharatpur",
        "Province 3, Chitawan, Ichchha Kamana",
        "Province 3, Chitawan, Kalika",
        "Province 3, Chitawan, Khairahani",
        "Province 3, Chitawan, Madi",
        "Province 3, Chitawan, Rapti",
        "Province 3, Chitawan, Ratnanagar",
        "Province 4, Gorkha, Aarughat",
        "Province 4, Gorkha, Ajirkot",
        "Province 4, Gorkha, Bhimsen",
        "Province 4, Gorkha, Chumanubri",
        "Province 4, Gorkha, Dharche",
        "Province 4, Gorkha, Gandaki",
        "Province 4, Gorkha, Gorkha",
        "Province 4, Gorkha, Palungtar",
        "Province 4, Gorkha, Shahid Lakhan",
        "Province 4, Gorkha, Siranchowk",
        "Province 4, Gorkha, Sulikot",
        "Province 4, Lamjung, Bensi Shahar",
        "Province 4, Lamjung, Dordi",
        "Province 4, Lamjung, Dudhapokhari",
        "Province 4, Lamjung, Kwhola Sothar",
        "Province 4, Lamjung, Madhya Nepal",
        "Province 4, Lamjung, Marshyangdi",
        "Province 4, Lamjung, Rainas",
        "Province 4, Lamjung, Sundarbazar",
        "Province 4, Tanahu, Aanbu Khaireni",
        "Province 4, Tanahu, Bandipur",
        "Province 4, Tanahu, Bhanu",
        "Province 4, Tanahu, Bhimad",
        "Province 4, Tanahu, Byas",
        "Province 4, Tanahu, Devghat",
        "Province 4, Tanahu, Ghiring",
        "Province 4, Tanahu, Myagde",
        "Province 4, Tanahu, Rhishing",
        "Province 4, Tanahu, Shuklagandaki",
        "Province 4, Syangja, Aandhikhola",
        "Province 4, Syangja, Arjun Choupari",
        "Province 4, Syangja, Bhirkot Municipaity",
        "Province 4, Syangja, Biruwa",
        "Province 4, Syangja, Chapakot",
        "Province 4, Syangja, Galyang",
        "Province 4, Syangja, Harinas",
        "Province 4, Syangja, Kaligandaki",
        "Province 4, Syangja, Phedikhola",
        "Province 4, Syangja, Putalibazar",
        "Province 4, Syangja, Walling",
        "Province 4, Kaski, Annapurna",
        "Province 4, Kaski, Machhapuchchhre",
        "Province 4, Kaski, Madi",
        "Province 4, Kaski, Pokhara Lekhnath",
        "Province 4, Kaski, Rupa",
        "Province 4, Manang, Chame",
        "Province 4, Manang, Naraphu",
        "Province 4, Manang, Nashong",
        "Province 4, Manang, Neshang",
        "Province 4, Mustang, Bahragaun Muktikshetra",
        "Province 4, Mustang, Dalome",
        "Province 4, Mustang, Gharpajhong",
        "Province 4, Mustang, Lomanthang",
        "Province 4, Mustang, Thasang",
        "Province 4, Myagdi, Annapurna",
        "Province 4, Myagdi, Beni",
        "Province 4, Myagdi, Dhawalagiri",
        "Province 4, Myagdi, Malika",
        "Province 4, Myagdi, Mangala",
        "Province 4, Myagdi, Raghuganga",
        "Province 4, Parbat, Bihadi",
        "Province 4, Parbat, Jaljala",
        "Province 4, Parbat, Kushma",
        "Province 4, Parbat, Mahashila",
        "Province 4, Parbat, Modi",
        "Province 4, Parbat, Paiyu",
        "Province 4, Parbat, Phalebas",
        "Province 4, Baglung, Badigad",
        "Province 4, Baglung, Baglung",
        "Province 4, Baglung, Bareng",
        "Province 4, Baglung, Dhorpatan",
        "Province 4, Baglung, Galkot",
        "Province 4, Baglung, Jaimuni",
        "Province 4, Baglung, Kathekhola",
        "Province 4, Baglung, Nisikhola",
        "Province 4, Baglung, Tamankhola",
        "Province 4, Baglung, Tarakhola",
        "Province 4, Nawalparasi, Binayi Tribeni",
        "Province 4, Nawalparasi, Bulingtar",
        "Province 4, Nawalparasi, Bungdikali",
        "Province 4, Nawalparasi, Devchuli",
        "Province 4, Nawalparasi, Gaidakot",
        "Province 4, Nawalparasi, Hupsekot",
        "Province 4, Nawalparasi, Kawasoti",
        "Province 4, Nawalparasi, Madhya Bindu",
        "Province 5, Gulmi, Chandrakot",
        "Province 5, Gulmi, Chhatrakot",
        "Province 5, Gulmi, Dhurkot",
        "Province 5, Gulmi, Gulmi Durbar Gaunpaika",
        "Province 5, Gulmi, Isma",
        "Province 5, Gulmi, Kali Gandaki",
        "Province 5, Gulmi, Madane",
        "Province 5, Gulmi, Malika",
        "Province 5, Gulmi, Musikot",
        "Province 5, Gulmi, Resunga",
        "Province 5, Gulmi, Ruru",
        "Province 5, Gulmi, Satyawoti",
        "Province 5, Palpa, Baganaskali",
        "Province 5, Palpa, Mathagadhi",
        "Province 5, Palpa, Nisdi",
        "Province 5, Palpa, Purbakhola",
        "Province 5, Palpa, Rainadevi Chhahara",
        "Province 5, Palpa, Rambha",
        "Province 5, Palpa, Rampur",
        "Province 5, Palpa, Ribdikot",
        "Province 5, Palpa, Tansen",
        "Province 5, Palpa, Tinau",
        "Province 5, Nawalparasi, Bardaghat",
        "Province 5, Nawalparasi, Palhinandan",
        "Province 5, Nawalparasi, Pratapapur",
        "Province 5, Nawalparasi, Ramgram",
        "Province 5, Nawalparasi, Sarawal",
        "Province 5, Nawalparasi, Sunawal",
        "Province 5, Nawalparasi, Susta",
        "Province 5, Rupandehi, Butwal",
        "Province 5, Rupandehi, Devdaha",
        "Province 5, Rupandehi, Gaidahawa",
        "Province 5, Rupandehi, Kanchan",
        "Province 5, Rupandehi, Kotahimai",
        "Province 5, Rupandehi, Lumbini Sanskritik",
        "Province 5, Rupandehi, Marchawari",
        "Province 5, Rupandehi, Mayadevi",
        "Province 5, Rupandehi, Om Satiya",
        "Province 5, Rupandehi, Rohini",
        "Province 5, Rupandehi, Sainamaina",
        "Province 5, Rupandehi, Sammarimai",
        "Province 5, Rupandehi, Siddharthanagar",
        "Province 5, Rupandehi, Siyari",
        "Province 5, Rupandehi, Suddhodhan",
        "Province 5, Rupandehi, Tilottama",
        "Province 5, Kapilbastu, Banganga",
        "Province 5, Kapilbastu, Bijayanagar",
        "Province 5, Kapilbastu, Buddhabhumi",
        "Province 5, Kapilbastu, Kapilbastu",
        "Province 5, Kapilbastu, Krishnanagar",
        "Province 5, Kapilbastu, Maharajganj",
        "Province 5, Kapilbastu, Mayadevi",
        "Province 5, Kapilbastu, Shivaraj",
        "Province 5, Kapilbastu, Shuddhodhan",
        "Province 5, Kapilbastu, Yasodhara",
        "Province 5, Arghakhanchi, Bhumikasthan",
        "Province 5, Arghakhanchi, Chhatradev",
        "Province 5, Arghakhanchi, Malarani",
        "Province 5, Arghakhanchi, Panini",
        "Province 5, Arghakhanchi, Sandhikharka",
        "Province 5, Arghakhanchi, Shitaganga",
        "Province 5, Pyuthan, Aairawati",
        "Province 5, Pyuthan, Gaumukhi",
        "Province 5, Pyuthan, Jhimaruk",
        "Province 5, Pyuthan, Mallarani",
        "Province 5, Pyuthan, Mandavi",
        "Province 5, Pyuthan, Naubahini",
        "Province 5, Pyuthan, Pyuthan",
        "Province 5, Pyuthan, Sarumarani",
        "Province 5, Pyuthan, Sworgadwari",
        "Province 5, Rolpa, Duikholi",
        "Province 5, Rolpa, Lungri",
        "Province 5, Rolpa, Madi",
        "Province 5, Rolpa, Rolpa",
        "Province 5, Rolpa, Runtigadhi",
        "Province 5, Rolpa, Subarnabati",
        "Province 5, Rolpa, Sukidaha",
        "Province 5, Rolpa, Sunchhahari",
        "Province 5, Rolpa, Thawang",
        "Province 5, Rolpa, Tribeni",
        "Province 5, Rukum, Bhoome",
        "Province 5, Rukum, Putha Uttanganga",
        "Province 5, Rukum, Sisne",
        "Province 5, Dang, Babai",
        "Province 5, Dang, Bangalachuli",
        "Province 5, Dang, Dangisharan",
        "Province 5, Dang, Gadhawa",
        "Province 5, Dang, Ghorahi",
        "Province 5, Dang, Lamahi",
        "Province 5, Dang, Rajpur",
        "Province 5, Dang, Rapti",
        "Province 5, Dang, Shantinagar",
        "Province 5, Dang, Tulsipur",
        "Province 5, Banke, Baijanath",
        "Province 5, Banke, Duduwa",
        "Province 5, Banke, Janaki",
        "Province 5, Banke, Khajura",
        "Province 5, Banke, Kohalpur",
        "Province 5, Banke, Narainapur",
        "Province 5, Banke, Nepalganj",
        "Province 5, Banke, Rapti Sonari",
        "Province 5, Bardiya, Badhaiyatal",
        "Province 5, Bardiya, Bansgadhi",
        "Province 5, Bardiya, Barbardiya",
        "Province 5, Bardiya, Geruwa",
        "Province 5, Bardiya, Gulariya",
        "Province 5, Bardiya, Madhuwan",
        "Province 5, Bardiya, Rajapur",
        "Province 5, Bardiya, Thakurbaba",
        "Province 6, Rukum, Aathabisakot",
        "Province 6, Rukum, Banphikot",
        "Province 6, Rukum, Chaurjahari",
        "Province 6, Rukum, Musikot",
        "Province 6, Rukum, Sanibheri",
        "Province 6, Rukum, Tribeni",
        "Province 6, Salyan, Bagachour",
        "Province 6, Salyan, Banagad Kupinde",
        "Province 6, Salyan, Chhatreshwori",
        "Province 6, Salyan, Darma",
        "Province 6, Salyan, Dhorchaur",
        "Province 6, Salyan, Kalimati",
        "Province 6, Salyan, Kapurkot",
        "Province 6, Salyan, Kumakh Malika",
        "Province 6, Salyan, Sharada",
        "Province 6, Salyan, Tribeni",
        "Province 6, Surkhet, Barahatal",
        "Province 6, Surkhet, Bheriganga",
        "Province 6, Surkhet, Birendranagar",
        "Province 6, Surkhet, Chaukune",
        "Province 6, Surkhet, Chingad",
        "Province 6, Surkhet, Gurbhakot",
        "Province 6, Surkhet, Lekabeshi",
        "Province 6, Surkhet, Panchapuri",
        "Province 6, Surkhet, Simta",
        "Province 6, Dailekh, Aathbis",
        "Province 6, Dailekh, Bhagawatimai",
        "Province 6, Dailekh, Bhairabi",
        "Province 6, Dailekh, Chamunda Bindrasaini",
        "Province 6, Dailekh, Dullu",
        "Province 6, Dailekh, Dungeshwor",
        "Province 6, Dailekh, Gurans",
        "Province 6, Dailekh, Mahabu",
        "Province 6, Dailekh, Narayan",
        "Province 6, Dailekh, Naumule",
        "Province 6, Dailekh, Thantikandh",
        "Province 6, Jajarkot, Barekot",
        "Province 6, Jajarkot, Bheri Malika",
        "Province 6, Jajarkot, Chhedagad",
        "Province 6, Jajarkot, Junichande",
        "Province 6, Jajarkot, Kuse",
        "Province 6, Jajarkot, Shivalaya",
        "Province 6, Jajarkot, Tribeni Nalagad",
        "Province 6, Dolpa, Chharka Tangsong",
        "Province 6, Dolpa, Dolpo Buddha",
        "Province 6, Dolpa, Jagadulla",
        "Province 6, Dolpa, Kaike",
        "Province 6, Dolpa, Mudkechula",
        "Province 6, Dolpa, Shey Phoksundo",
        "Province 6, Dolpa, Thulibheri",
        "Province 6, Dolpa, Tripurasundari",
        "Province 6, Jumla, Chandannath",
        "Province 6, Jumla, Guthichaur",
        "Province 6, Jumla, Hima",
        "Province 6, Jumla, Kanaka Sundari Gaun Palika",
        "Province 6, Jumla, Patarasi",
        "Province 6, Jumla, Sinja",
        "Province 6, Jumla, Tatopani",
        "Province 6, Jumla, Tila",
        "Province 6, Kalikot, Kalika",
        "Province 6, Kalikot, Khandachakra",
        "Province 6, Kalikot, Mahawai",
        "Province 6, Kalikot, Naraharinath",
        "Province 6, Kalikot, Pachal Jharana",
        "Province 6, Kalikot, Palata",
        "Province 6, Kalikot, Raskot",
        "Province 6, Kalikot, Sanni Tribeni",
        "Province 6, Kalikot, Tilagupha",
        "Province 6, Mugu, Chhayanath Rara",
        "Province 6, Mugu, Khatyad",
        "Province 6, Mugu, Mugumakarmarog",
        "Province 6, Mugu, Soru",
        "Province 6, Humla, Adanchuli",
        "Province 6, Humla, Chankheli",
        "Province 6, Humla, Kharpunath",
        "Province 6, Humla, Namkha",
        "Province 6, Humla, Sarkegad",
        "Province 6, Humla, Simkot",
        "Province 6, Humla, Tanjakot",
        "Province 7, Bajura, Badimalika",
        "Province 7, Bajura, Budhiganga",
        "Province 7, Bajura, Budhinanda",
        "Province 7, Bajura, Chhededaha",
        "Province 7, Bajura, Gaumul",
        "Province 7, Bajura, Himali",
        "Province 7, Bajura, Pandab Gufa",
        "Province 7, Bajura, Swami Kartik",
        "Province 7, Bajura, Tribeni",
        "Province 7, Bajhang, Bitthadchir",
        "Province 7, Bajhang, Bungal",
        "Province 7, Bajhang, Chhabis Pathibhara",
        "Province 7, Bajhang, Durgathali",
        "Province 7, Bajhang, Jayaprithbi",
        "Province 7, Bajhang, Kanda",
        "Province 7, Bajhang, Kedarsyun",
        "Province 7, Bajhang, Khaptad Chhanna",
        "Province 7, Bajhang, Masta",
        "Province 7, Bajhang, Surma",
        "Province 7, Bajhang, Talkot",
        "Province 7, Bajhang, Thalara",
        "Province 7, Achham, Bannigadhi Jayagadh",
        "Province 7, Achham, Chaurpati",
        "Province 7, Achham, Dhakari",
        "Province 7, Achham, Kamal bazar",
        "Province 7, Achham, Mangalsen",
        "Province 7, Achham, Mellekh",
        "Province 7, Achham, Panchdebal Binayak",
        "Province 7, Achham, Ramaroshan",
        "Province 7, Achham, Sanphebagar",
        "Province 7, Achham, Turmakhand",
        "Province 7, Doti, Aadarsha",
        "Province 7, Doti, Badi Kedar",
        "Province 7, Doti, Bogatan",
        "Province 7, Doti, Dipayal Silgadhi",
        "Province 7, Doti, Jorayal",
        "Province 7, Doti, K.I. Singh",
        "Province 7, Doti, Purbichouki",
        "Province 7, Doti, Sayal",
        "Province 7, Doti, Shikhar",
        "Province 7, Kailali, Bardagoriya",
        "Province 7, Kailali, Bhajani",
        "Province 7, Kailali, Chure",
        "Province 7, Kailali, Dhangadhi",
        "Province 7, Kailali, Gauriganga",
        "Province 7, Kailali, Ghodaghodi",
        "Province 7, Kailali, Godawari",
        "Province 7, Kailali, Janaki",
        "Province 7, Kailali, Joshipur",
        "Province 7, Kailali, Kailari",
        "Province 7, Kailali, Lamki Chuha",
        "Province 7, Kailali, Mohanyal",
        "Province 7, Kailali, Tikapur",
        "Province 7, Kanchanpur, Bedkot",
        "Province 7, Kanchanpur, Beldandi",
        "Province 7, Kanchanpur, Belouri",
        "Province 7, Kanchanpur, Bhimdatta",
        "Province 7, Kanchanpur, Krishnapur",
        "Province 7, Kanchanpur, Laljhadi",
        "Province 7, Kanchanpur, Mahakali",
        "Province 7, Kanchanpur, Punarbas",
        "Province 7, Kanchanpur, Shuklaphanta",
        "Province 7, Dadeldhura, Aalital",
        "Province 7, Dadeldhura, Ajayameru",
        "Province 7, Dadeldhura, Amargadhi",
        "Province 7, Dadeldhura, Bhageshwor",
        "Province 7, Dadeldhura, Ganyapdhura",
        "Province 7, Dadeldhura, Nawadurga",
        "Province 7, Dadeldhura, Parashuram",
        "Province 7, Baitadi, Dasharathchand",
        "Province 7, Baitadi, Dilasaini",
        "Province 7, Baitadi, Dogada Kedar",
        "Province 7, Baitadi, Melauli",
        "Province 7, Baitadi, Pancheshwor",
        "Province 7, Baitadi, Patam",
        "Province 7, Baitadi, Puchaundi",
        "Province 7, Baitadi, Shivanath",
        "Province 7, Baitadi, Sigas",
        "Province 7, Baitadi, Surnaya",
        "Province 7, Darchula, Apihimal",
        "Province 7, Darchula, Byas",
        "Province 7, Darchula, Duhun",
        "Province 7, Darchula, Lekam",
        "Province 7, Darchula, Mahakali",
        "Province 7, Darchula, Malikarjun",
        "Province 7, Darchula, Marma",
        "Province 7, Darchula, Naugad ",
        "Province 7, Darchula, Shailyashikhar"

        ]
    
}

const reducer =(state=initialstate,action) => {
    switch(action.type){
        case 'Update_Lan':
            let newstate = state;
            newstate.lan = action.data;
            return newstate;
            

        default:
            return state;

    }
}

export default combineReducers({
    reducer,
    checkSymptom: checkSymptomReducer,
  
});
