import { combineReducers } from "redux";

import checkSymptomReducer from "./checkSymptomReducer";

const initialstate = {
    lan: 'np',
    municipalities : [
        "Province 1, Bhojpur, Aamchok",
        "Province 1, Bhojpur, Arun",
        "Province 1, Bhojpur, Bhojpur",
        "Province 1, Bhojpur, Hatuwagadhi",
        "Province 1, Bhojpur, Pauwadungma",
        "Province 1, Bhojpur, Ramprasad Rai",
        "Province 1, Bhojpur, Sadananda",
        "Province 1, Bhojpur, Salpasilichho",
        "Province 1, Bhojpur, Temkemaiyung",
        "Province 1, Dhankuta, Chaubise",
        "Province 1, Dhankuta, Chhathar Jorpati",
        "Province 1, Dhankuta, Dhankuta",
        "Province 1, Dhankuta, Mahalaxmi",
        "Province 1, Dhankuta, Pakhribas",
        "Province 1, Dhankuta, Sangurigadhi",
        "Province 1, Dhankuta, Shahidbhumi",
        "Province 1, Ilam, Chulachuli",
        "Province 1, Ilam, Deumai",
        "Province 1, Ilam, Ilam",
        "Province 1, Ilam, Mai",
        "Province 1, Ilam, Maijogmai",
        "Province 1, Ilam, Mangsebung",
        "Province 1, Ilam, Phakphokthum",
        "Province 1, Ilam, Rong",
        "Province 1, Ilam, Sandakpur",
        "Province 1, Ilam, Suryodaya",
        "Province 1, Jhapa, Arjundhara",
        "Province 1, Jhapa, Bahradashi",
        "Province 1, Jhapa, Bhadrapur",
        "Province 1, Jhapa, Birtamod",
        "Province 1, Jhapa, Buddhashanti",
        "Province 1, Jhapa, Damak",
        "Province 1, Jhapa, Gauradaha",
        "Province 1, Jhapa, Gaurigunj",
        "Province 1, Jhapa, Haldibari",
        "Province 1, Jhapa, Jhapa",
        "Province 1, Jhapa, Kachankawal",
        "Province 1, Jhapa, Kamal",
        "Province 1, Jhapa, Kankai",
        "Province 1, Jhapa, Mechinagar",
        "Province 1, Jhapa, Shivasatakshi",
        "Province 1, Khotang, Ainselukharka",
        "Province 1, Khotang, Barahapokhari",
        "Province 1, Khotang, Diktel Rupakot Majhuwagadhi",
        "Province 1, Khotang, Diprung Chuichumma",
        "Province 1, Khotang, Halesi Tuwachung",
        "Province 1, Khotang, Jantedhunga",
        "Province 1, Khotang, Kepilasgadhi",
        "Province 1, Khotang, Khotehang",
        "Province 1, Khotang, Rawabesi",
        "Province 1, Khotang, Sakela",
        "Province 1, Morang, Belbari",
        "Province 1, Morang, Biratnagar",
        "Province 1, Morang, Budhiganga",
        "Province 1, Morang, Dhanpalthan",
        "Province 1, Morang, Gramthan",
        "Province 1, Morang, Jahada",
        "Province 1, Morang, Kanepokhari",
        "Province 1, Morang, Katahari",
        "Province 1, Morang, Kerabari",
        "Province 1, Morang, Letang",
        "Province 1, Morang, Miklajung",
        "Province 1, Morang, Pathari Shanishchare",
        "Province 1, Morang, Rangeli",
        "Province 1, Morang, Ratuwamai",
        "Province 1, Morang, Sundarharaincha",
        "Province 1, Morang, Sunbarsi",
        "Province 1, Morang, Urlabari",
        "Province 1, Okhaldhunga, Baganaskali",
        "Province 1, Okhaldhunga, Mathagadhi",
        "Province 1, Okhaldhunga, Nisdi",
        "Province 1, Okhaldhunga, Purbakhola",
        "Province 1, Okhaldhunga, Rainadevi Chhahara",
        "Province 1, Okhaldhunga, Rambha",
        "Province 1, Okhaldhunga, Rampur",
        "Province 1, Okhaldhunga, Ribdikot",
        "Province 1, Okhaldhunga, Tansen",
        "Province 1, Okhaldhunga, Tinau",
        "Province 1, Panchthar, Bihadi",
        "Province 1, Panchthar, Jaljala",
        "Province 1, Panchthar, Kushma",
        "Province 1, Panchthar, Mahashila",
        "Province 1, Panchthar, Modi",
        "Province 1, Panchthar, Paiyun",
        "Province 1, Panchthar, Phalebas",
        "Province 1, Sankhuwasabha, Bagmati",
        "Province 1, Sankhuwasabha, Balara",
        "Province 1, Sankhuwasabha, Barahathawa",
        "Province 1, Sankhuwasabha, Basbariya",
        "Province 1, Sankhuwasabha, Bishnu",
        "Province 1, Sankhuwasabha, Brahmapuri",
        "Province 1, Sankhuwasabha, Chakraghatta",
        "Province 1, Sankhuwasabha, Chandranagar",
        "Province 1, Sankhuwasabha, Dhanakaul",
        "Province 1, Sankhuwasabha, Godaita",
        "Province 1, Sankhuwasabha, Haripur",
        "Province 1, Sankhuwasabha, Haripurwa",
        "Province 1, Sankhuwasabha, Hariwan",
        "Province 1, Sankhuwasabha, Ishworpur",
        "Province 1, Sankhuwasabha, Kabilasi",
        "Province 1, Sankhuwasabha, Kaudena",
        "Province 1, Sankhuwasabha, Lalbandi",
        "Province 1, Sankhuwasabha, Malangawa",
        "Province 1, Sankhuwasabha, Parsa",
        "Province 1, Sankhuwasabha, Ramnagar",
        "Province 1, Solukhumbu, Barahatal",
        "Province 1, Solukhumbu, Bheriganga",
        "Province 1, Solukhumbu, Birendranagar",
        "Province 1, Solukhumbu, Chaukune",
        "Province 1, Solukhumbu, Chingad",
        "Province 1, Solukhumbu, Gurbhakot",
        "Province 1, Solukhumbu, Lekbesi",
        "Province 1, Solukhumbu, Panchapuri",
        "Province 1, Solukhumbu, Simta",
        "Province 1, Sunsari, Aandhikhola",
        "Province 1, Sunsari, Arjunchaupari",
        "Province 1, Sunsari, Bhirkot",
        "Province 1, Sunsari, Biruwa",
        "Province 1, Sunsari, Chapakot",
        "Province 1, Sunsari, Galyang",
        "Province 1, Sunsari, Harinas",
        "Province 1, Sunsari, Kaligandaki",
        "Province 1, Sunsari, Phedikhola",
        "Province 1, Sunsari, Putalibazar",
        "Province 1, Sunsari, Waling",
        "Province 1, Taplejung, Belaka",
        "Province 1, Taplejung, Chaudandigadhi",
        "Province 1, Taplejung, Katari",
        "Province 1, Taplejung, Koshi Tappu Wildlife Reserve",
        "Province 1, Taplejung, Rautamai",
        "Province 1, Taplejung, Sunkoshi",
        "Province 1, Taplejung, Tapli",
        "Province 1, Taplejung, Triyuga",
        "Province 1, Taplejung, Udayapurgadhi",
        "Province 1, Terhathum, Bardaghat",
        "Province 1, Terhathum, Palhinandan",
        "Province 1, Terhathum, Pratappur",
        "Province 1, Terhathum, Ramgram",
        "Province 1, Terhathum, Sarawal",
        "Province 1, Terhathum, Sunwal",
        "Province 1, Terhathum, Susta",
        "Province 1, Udayapur, Aathbiskot",
        "Province 1, Udayapur, Banphikot",
        "Province 1, Udayapur, Chaurjahari",
        "Province 1, Udayapur, Musikot",
        "Province 1, Udayapur, Sanibheri",
        "Province 1, Udayapur, Triveni",
        "Province 2, Bara, Aadarsha Kotwal",
        "Province 2, Bara, Baragadhi",
        "Province 2, Bara, Bishrampur",
        "Province 2, Bara, Devtal",
        "Province 2, Bara, Jitpur Simra",
        "Province 2, Bara, Kalaiya",
        "Province 2, Bara, Karaiyamai",
        "Province 2, Bara, Kolhawi",
        "Province 2, Bara, Mahagadhimai",
        "Province 2, Bara, Nijgadh",
        "Province 2, Bara, Pachrauta",
        "Province 2, Bara, Parsa Wildlife Reserve",
        "Province 2, Bara, Parwanipur",
        "Province 2, Bara, Pheta",
        "Province 2, Bara, Prasauni",
        "Province 2, Bara, Simraungadh",
        "Province 2, Bara, Suvarna",
        "Province 2, Siraha, Barahakshetra",
        "Province 2, Siraha, Barju",
        "Province 2, Siraha, Bhokraha Narsingh",
        "Province 2, Siraha, Dewangunj",
        "Province 2, Siraha, Dharan",
        "Province 2, Siraha, Duhabi",
        "Province 2, Siraha, Gadhi",
        "Province 2, Siraha, Harinagar",
        "Province 2, Siraha, Inaruwa",
        "Province 2, Siraha, Itahari",
        "Province 2, Siraha, Koshi",
        "Province 2, Siraha, Koshi Tappu Wildlife Reserve",
        "Province 2, Siraha, Ramdhuni",
        "Province 2, Saptari, Dudhauli",
        "Province 2, Saptari, Ghyanglekh",
        "Province 2, Saptari, Golanjor",
        "Province 2, Saptari, Hariharpurgadhi",
        "Province 2, Saptari, Kamalamai",
        "Province 2, Saptari, Marin",
        "Province 2, Saptari, Phikkal",
        "Province 2, Saptari, Sunkoshi",
        "Province 2, Saptari, Tinpatan",
        "Province 2, Sarlahi, Bahrabise",
        "Province 2, Sarlahi, Balephi",
        "Province 2, Sarlahi, Bhotekoshi",
        "Province 2, Sarlahi, Chautara Sangachokgadhi",
        "Province 2, Sarlahi, Helambu",
        "Province 2, Sarlahi, Indrawati",
        "Province 2, Sarlahi, Jugal",
        "Province 2, Sarlahi, Lisankhupakhar",
        "Province 2, Sarlahi, Melamchi",
        "Province 2, Sarlahi, Panchpokhari Thangpal",
        "Province 2, Sarlahi, Sunkoshi",
        "Province 2, Sarlahi, Tripurasundari",
        "Province 2, Parsa, Airawati",
        "Province 2, Parsa, Gaumukhi",
        "Province 2, Parsa, Jhimruk",
        "Province 2, Parsa, Mallarani",
        "Province 2, Parsa, Mandavi",
        "Province 2, Parsa, Naubahini",
        "Province 2, Parsa, Pyuthan",
        "Province 2, Parsa, Sarumarani",
        "Province 2, Parsa, Swargadwari",
        "Province 2, Rautahat, Gangadev",
        "Province 2, Rautahat, Lungri",
        "Province 2, Rautahat, Madi",
        "Province 2, Rautahat, Parivartan",
        "Province 2, Rautahat, Rolpa",
        "Province 2, Rautahat, Runtigadhi",
        "Province 2, Rautahat, Sunchhahari",
        "Province 2, Rautahat, Sunil Smriti",
        "Province 2, Rautahat, Thawang",
        "Province 2, Rautahat, Triveni",
        "Province 2, Mahottari, Aurahi",
        "Province 2, Mahottari, Balawa",
        "Province 2, Mahottari, Bardibas",
        "Province 2, Mahottari, Bhangaha",
        "Province 2, Mahottari, Ekdara",
        "Province 2, Mahottari, Gaushala",
        "Province 2, Mahottari, Jaleshwor",
        "Province 2, Mahottari, Loharpatti",
        "Province 2, Mahottari, Mahottari",
        "Province 2, Mahottari, Manara Shiswa",
        "Province 2, Mahottari, Matihani",
        "Province 2, Mahottari, Pipara",
        "Province 2, Mahottari, Ramgopalpur",
        "Province 2, Mahottari, Samsi",
        "Province 2, Mahottari, Sonma",
        "Province 2, Dhanusa, Aurahi",
        "Province 2, Dhanusa, Bateshwor",
        "Province 2, Dhanusa, Bideha",
        "Province 2, Dhanusa, Dhanauji",
        "Province 2, Dhanusa, Dhanusadham",
        "Province 2, Dhanusa, Ganeshman Charnath",
        "Province 2, Dhanusa, Hansapur",
        "Province 2, Dhanusa, Janaknandini",
        "Province 2, Dhanusa, Janakpurdham",
        "Province 2, Dhanusa, Kamala",
        "Province 2, Dhanusa, Kshireshwornath",
        "Province 2, Dhanusa, Laxminiya",
        "Province 2, Dhanusa, Mithila",
        "Province 2, Dhanusa, Mithila Bihari",
        "Province 2, Dhanusa, Mukhiyapatti Musaharmiya",
        "Province 2, Dhanusa, Nagarain",
        "Province 2, Dhanusa, Sabaila",
        "Province 2, Dhanusa, Shahidnagar",
        "Province 3, Chitwan, Bharatpur",
        "Province 3, Chitwan, Chitawan National Park",
        "Province 3, Chitwan, Ichchhakamana",
        "Province 3, Chitwan, Kalika",
        "Province 3, Chitwan, Khairahani",
        "Province 3, Chitwan, Madi",
        "Province 3, Chitwan, Rapti",
        "Province 3, Chitwan, Ratnanagar",
        "Province 3, Dolakha, Baiteshwor",
        "Province 3, Dolakha, Bhimeshwor",
        "Province 3, Dolakha, Bigu",
        "Province 3, Dolakha, Gaurishankar",
        "Province 3, Dolakha, Jiri",
        "Province 3, Dolakha, Kalinchok",
        "Province 3, Dolakha, Melung",
        "Province 3, Dolakha, Shailung",
        "Province 3, Dolakha, Tamakoshi",
        "Province 3, Makwanpur, Bagmati",
        "Province 3, Makwanpur, Bakaiya",
        "Province 3, Makwanpur, Bhimphedi",
        "Province 3, Makwanpur, Chitawan National Park",
        "Province 3, Makwanpur, Hetaunda",
        "Province 3, Makwanpur, Indrasarowar",
        "Province 3, Makwanpur, Kailash",
        "Province 3, Makwanpur, Makwanpurgadhi",
        "Province 3, Makwanpur, Manahari",
        "Province 3, Makwanpur, Parsa Wildlife Reserve",
        "Province 3, Makwanpur, Raksirang",
        "Province 3, Makwanpur, Thaha",
        "Province 3, Lalitpur, Bagmati",
        "Province 3, Lalitpur, Godawari",
        "Province 3, Lalitpur, Konjyosom",
        "Province 3, Lalitpur, Lalitpur",
        "Province 3, Lalitpur, Mahalaxmi",
        "Province 3, Lalitpur, Mahankal",
        "Province 3, Dhading, Benighat Rorang",
        "Province 3, Dhading, Dhunibesi",
        "Province 3, Dhading, Gajuri",
        "Province 3, Dhading, Galchhi",
        "Province 3, Dhading, Gangajamuna",
        "Province 3, Dhading, Jwalamukhi",
        "Province 3, Dhading, Khaniyabas",
        "Province 3, Dhading, Netrawati Dabjong",
        "Province 3, Dhading, Nilkantha",
        "Province 3, Dhading, Rubivalley",
        "Province 3, Dhading, Siddhalek",
        "Province 3, Dhading, Thakre",
        "Province 3, Dhading, Tripurasundari",
        "Province 3, Kathmandu, Budhanilkantha",
        "Province 3, Kathmandu, Chandragiri",
        "Province 3, Kathmandu, Dakshinkali",
        "Province 3, Kathmandu, Gokarneshwor",
        "Province 3, Kathmandu, Kageshwori Manohara",
        "Province 3, Kathmandu, Kathmandu",
        "Province 3, Kathmandu, Kirtipur",
        "Province 3, Kathmandu, Nagarjun",
        "Province 3, Kathmandu, Shankharapur",
        "Province 3, Kathmandu, Tarakeshwor",
        "Province 3, Kathmandu, Tokha",
        "Province 3, Kavrepalanchowk, Banepa",
        "Province 3, Kavrepalanchowk, Bethanchok",
        "Province 3, Kavrepalanchowk, Bhumlu",
        "Province 3, Kavrepalanchowk, Chauri Deurali",
        "Province 3, Kavrepalanchowk, Dhulikhel",
        "Province 3, Kavrepalanchowk, Khanikhola",
        "Province 3, Kavrepalanchowk, Mahabharat",
        "Province 3, Kavrepalanchowk, Mandan Deupur",
        "Province 3, Kavrepalanchowk, Namobuddha",
        "Province 3, Kavrepalanchowk, Panauti",
        "Province 3, Kavrepalanchowk, Panchkhal",
        "Province 3, Kavrepalanchowk, Roshi",
        "Province 3, Kavrepalanchowk, Temal",
        "Province 3, Ramechhap, Gosainkunda",
        "Province 3, Ramechhap, Kalika",
        "Province 3, Ramechhap, Naukunda",
        "Province 3, Ramechhap, Parbatikunda",
        "Province 3, Ramechhap, Uttargaya",
        "Province 3, Rasuwa, Baudhimai",
        "Province 3, Rasuwa, Brindaban",
        "Province 3, Rasuwa, Chandrapur",
        "Province 3, Rasuwa, Dewahi Gonahi",
        "Province 3, Rasuwa, Durgabhagawati",
        "Province 3, Rasuwa, Gadhimai",
        "Province 3, Rasuwa, Garuda",
        "Province 3, Rasuwa, Gaur",
        "Province 3, Rasuwa, Gujara",
        "Province 3, Rasuwa, Ishnath",
        "Province 3, Rasuwa, Katahariya",
        "Province 3, Rasuwa, Madhavnarayan",
        "Province 3, Rasuwa, Maulapur",
        "Province 3, Rasuwa, Paroha",
        "Province 3, Rasuwa, Phatuwa Bijayapur",
        "Province 3, Rasuwa, Rajdevi",
        "Province 3, Rasuwa, Rajpur",
        "Province 3, Rasuwa, Yamunamai",
        "Province 3, Nuwakot, Champadevi",
        "Province 3, Nuwakot, Chishankhugadhi",
        "Province 3, Nuwakot, Khijidemba",
        "Province 3, Nuwakot, Likhu",
        "Province 3, Nuwakot, Manebhanjyang",
        "Province 3, Nuwakot, Molung",
        "Province 3, Nuwakot, Siddhicharan",
        "Province 3, Nuwakot, Sunkoshi",
        "Province 3, Sindhuli, Arnama",
        "Province 3, Sindhuli, Aurahi",
        "Province 3, Sindhuli, Bariyarpatti",
        "Province 3, Sindhuli, Bhagwanpur",
        "Province 3, Sindhuli, Bishnupur",
        "Province 3, Sindhuli, Dhangadhimai",
        "Province 3, Sindhuli, Golbazar",
        "Province 3, Sindhuli, Kalyanpur",
        "Province 3, Sindhuli, Karjanha",
        "Province 3, Sindhuli, Lahan",
        "Province 3, Sindhuli, Laxmipur Patari",
        "Province 3, Sindhuli, Mirchaiya",
        "Province 3, Sindhuli, Naraha",
        "Province 3, Sindhuli, Navarajpur",
        "Province 3, Sindhuli, Sakhuwa Nankarkatti",
        "Province 3, Sindhuli, Siraha",
        "Province 3, Sindhuli, Sukhipur",
        "Province 3, Sindhupalchowk, Khumbu Pasanglhamu",
        "Province 3, Sindhupalchowk, Likhupike",
        "Province 3, Sindhupalchowk, Mahakulung",
        "Province 3, Sindhupalchowk, Mapya Dudhkoshi",
        "Province 3, Sindhupalchowk, Nechasalyan",
        "Province 3, Sindhupalchowk, Solu Dudhkunda",
        "Province 3, Sindhupalchowk, Sotang",
        "Province 3, Sindhupalchowk, Thulung Dudhkoshi",
        "Province 3, Bhaktapur, Bhaktapur",
        "Province 3, Bhaktapur, Changunarayan",
        "Province 3, Bhaktapur, Madhyapur Thimi",
        "Province 3, Bhaktapur, Suryabinayak",
        "Province 4, Kaski, Annapurna",
        "Province 4, Kaski, Machhapuchchhre",
        "Province 4, Kaski, Madi",
        "Province 4, Kaski, Pokhara",
        "Province 4, Kaski, Rupa",
        "Province 4, Syangja, Aathrai Triveni",
        "Province 4, Syangja, Maiwakhola",
        "Province 4, Syangja, Marin",
        "Province 4, Syangja, Mikwakhola",
        "Province 4, Syangja, Pathibhara Yangwarak",
        "Province 4, Syangja, Phaktanglung",
        "Province 4, Syangja, Phungling",
        "Province 4, Syangja, Sidingwa",
        "Province 4, Syangja, Sirijangha",
        "Province 4, Tanahu, Aatharai",
        "Province 4, Tanahu, Chhathar",
        "Province 4, Tanahu, Laligurans",
        "Province 4, Tanahu, Menchhayayem",
        "Province 4, Tanahu, Myanglung",
        "Province 4, Tanahu, Phedap",
        "Province 4, Mustang, Baragung Muktikshetra",
        "Province 4, Mustang, Gharpajhong",
        "Province 4, Mustang, Lo-Ghekar Damodarkunda",
        "Province 4, Mustang, Lomanthang",
        "Province 4, Mustang, Thasang",
        "Province 4, Myagdi, Annapurna",
        "Province 4, Myagdi, Beni",
        "Province 4, Myagdi, Dhawalagiri",
        "Province 4, Myagdi, Dhorpatan Hunting Reserve",
        "Province 4, Myagdi, Malika",
        "Province 4, Myagdi, Mangala",
        "Province 4, Myagdi, Raghuganga",
        "Province 4, Nawalparasi East, Baudikali",
        "Province 4, Nawalparasi East, Binayi Triveni",
        "Province 4, Nawalparasi East, Bulingtar",
        "Province 4, Nawalparasi East, Chitawan National Park",
        "Province 4, Nawalparasi East, Devchuli",
        "Province 4, Nawalparasi East, Gaindakot",
        "Province 4, Nawalparasi East, Hupsekot",
        "Province 4, Nawalparasi East, Kawasoti",
        "Province 4, Nawalparasi East, Madhyabindu",
        "Province 4, Parbat, Bahudarmai",
        "Province 4, Parbat, Bindabasini",
        "Province 4, Parbat, Birgunj",
        "Province 4, Parbat, Chhipaharmai",
        "Province 4, Parbat, Chitwan National Park",
        "Province 4, Parbat, Dhobini",
        "Province 4, Parbat, Jagarnathpur",
        "Province 4, Parbat, Jirabhawani",
        "Province 4, Parbat, Kalikamai",
        "Province 4, Parbat, Pakaha Mainpur",
        "Province 4, Parbat, Parsagadhi",
        "Province 4, Parbat, Paterwa Sugauli",
        "Province 4, Parbat, Pokhariya",
        "Province 4, Parbat, Sakhuwa Prasauni",
        "Province 4, Parbat, Thori",
        "Province 4, Baglung, Badigad",
        "Province 4, Baglung, Baglung",
        "Province 4, Baglung, Bareng",
        "Province 4, Baglung, Dhorpatan Hunting Reserve",
        "Province 4, Baglung, Dhorpatan",
        "Province 4, Baglung, Galkot",
        "Province 4, Baglung, Jaimini",
        "Province 4, Baglung, Kathekhola",
        "Province 4, Baglung, Nisikhola",
        "Province 4, Baglung, Tamankhola",
        "Province 4, Baglung, Tarakhola",
        "Province 4, Lamjung, Besishahar",
        "Province 4, Lamjung, Dordi",
        "Province 4, Lamjung, Dudhpokhari",
        "Province 4, Lamjung, Kwholasothar",
        "Province 4, Lamjung, Madhyanepal",
        "Province 4, Lamjung, Marsyangdi",
        "Province 4, Lamjung, Rainas",
        "Province 4, Lamjung, Sundarbazar",
        "Province 4, Manang, Chame",
        "Province 4, Manang, Manang Ngisyang",
        "Province 4, Manang, Narpabhumi",
        "Province 4, Manang, Nason",
        "Province 4, Gorkha, Aarughat",
        "Province 4, Gorkha, Ajirkot",
        "Province 4, Gorkha, Barpak Sulikot",
        "Province 4, Gorkha, Bhimsen Thapa",
        "Province 4, Gorkha, Chumnubri",
        "Province 4, Gorkha, Dharche",
        "Province 4, Gorkha, Gandaki",
        "Province 4, Gorkha, Gorkha",
        "Province 4, Gorkha, Palungtar",
        "Province 4, Gorkha, Shahid Lakhan",
        "Province 4, Gorkha, Siranchok",
        "Province 5, Gulmi, Chandrakot",
        "Province 5, Gulmi, Chhatrakot",
        "Province 5, Gulmi, Dhurkot",
        "Province 5, Gulmi, Gulmidarbar",
        "Province 5, Gulmi, Isma",
        "Province 5, Gulmi, Kaligandaki",
        "Province 5, Gulmi, Madane",
        "Province 5, Gulmi, Malika",
        "Province 5, Gulmi, Musikot",
        "Province 5, Gulmi, Resunga",
        "Province 5, Gulmi, Ruru",
        "Province 5, Gulmi, Satyawati",
        "Province 5, Arghakhanchi, Bhumikasthan",
        "Province 5, Arghakhanchi, Chhatradev",
        "Province 5, Arghakhanchi, Malarani",
        "Province 5, Arghakhanchi, Panini",
        "Province 5, Arghakhanchi, Sandhikharka",
        "Province 5, Arghakhanchi, Shitganga",
        "Province 5, Dang, Babai",
        "Province 5, Dang, Bangalachuli",
        "Province 5, Dang, Dangisharan",
        "Province 5, Dang, Gadhawa",
        "Province 5, Dang, Ghorahi",
        "Province 5, Dang, Lamahi",
        "Province 5, Dang, Rajpur",
        "Province 5, Dang, Rapti",
        "Province 5, Dang, Shantinagar",
        "Province 5, Dang, Tulsipur",
        "Province 5, Kapilbastu, Banganga",
        "Province 5, Kapilbastu, Bijayanagar",
        "Province 5, Kapilbastu, Buddhabhumi",
        "Province 5, Kapilbastu, Kapilbastu",
        "Province 5, Kapilbastu, Krishnanagar",
        "Province 5, Kapilbastu, Maharajgunj",
        "Province 5, Kapilbastu, Mayadevi",
        "Province 5, Kapilbastu, Shivaraj",
        "Province 5, Kapilbastu, Shuddhodan",
        "Province 5, Kapilbastu, Yashodhara",
        "Province 5, Pyuthan, Doramba",
        "Province 5, Pyuthan, Gokulganga",
        "Province 5, Pyuthan, Khandadevi",
        "Province 5, Pyuthan, Likhu Tamakoshi",
        "Province 5, Pyuthan, Manthali",
        "Province 5, Pyuthan, Ramechhap",
        "Province 5, Pyuthan, Sunapati",
        "Province 5, Pyuthan, Umakunda",
        "Province 5, Rolpa, Bhume",
        "Province 5, Rolpa, Dhorpatan Hunting Reserve",
        "Province 5, Rolpa, Putha Uttarganga",
        "Province 5, Rolpa, Sisne",
        "Province 5, Nawalparasi West, Belkotgadhi",
        "Province 5, Nawalparasi West, Bidur",
        "Province 5, Nawalparasi West, Dupcheshwor",
        "Province 5, Nawalparasi West, Kakani",
        "Province 5, Nawalparasi West, Kispang",
        "Province 5, Nawalparasi West, Langtang National Park",
        "Province 5, Nawalparasi West, Likhu",
        "Province 5, Nawalparasi West, Myagang",
        "Province 5, Nawalparasi West, Panchakanya",
        "Province 5, Nawalparasi West, Shivapuri",
        "Province 5, Nawalparasi West, Shivapuri Watershed And Wildlife Reserve",
        "Province 5, Nawalparasi West, Suryagadhi",
        "Province 5, Nawalparasi West, Tadi",
        "Province 5, Nawalparasi West, Tarakeshwor",
        "Province 5, Palpa, Hilihang",
        "Province 5, Palpa, Kummayak",
        "Province 5, Palpa, Miklajung",
        "Province 5, Palpa, Phalelung",
        "Province 5, Palpa, Phalgunanda",
        "Province 5, Palpa, Phidim",
        "Province 5, Palpa, Tumbewa",
        "Province 5, Palpa, Yangwarak",
        "Province 5, Banke, Baijanath",
        "Province 5, Banke, Duduwa",
        "Province 5, Banke, Janaki",
        "Province 5, Banke, Khajura",
        "Province 5, Banke, Kohalpur",
        "Province 5, Banke, Narainapur",
        "Province 5, Banke, Nepalgunj",
        "Province 5, Banke, Rapti Sonari",
        "Province 5, Rukum East, Butwal",
        "Province 5, Rukum East, Devdaha",
        "Province 5, Rukum East, Gaidahawa",
        "Province 5, Rukum East, Kanchan",
        "Province 5, Rukum East, Kotahimai",
        "Province 5, Rukum East, Lumbini Sanskritik Development Area",
        "Province 5, Rukum East, Lumbini Sanskritik",
        "Province 5, Rukum East, Marchawari",
        "Province 5, Rukum East, Mayadevi",
        "Province 5, Rukum East, Omsatiya",
        "Province 5, Rukum East, Rohini",
        "Province 5, Rukum East, Sainamaina",
        "Province 5, Rukum East, Sammarimai",
        "Province 5, Rukum East, Shuddhodan",
        "Province 5, Rukum East, Siddharthanagar",
        "Province 5, Rukum East, Siyari",
        "Province 5, Rukum East, Tilottama",
        "Province 5, Rupandehi, Bhotkhola",
        "Province 5, Rupandehi, Chainpur",
        "Province 5, Rupandehi, Chichila",
        "Province 5, Rupandehi, Dharmadevi",
        "Province 5, Rupandehi, Khandbari",
        "Province 5, Rupandehi, Madi",
        "Province 5, Rupandehi, Makalu",
        "Province 5, Rupandehi, Panchkhapan",
        "Province 5, Rupandehi, Sabhapokhari",
        "Province 5, Rupandehi, Silichong",
        "Province 5, Bardiya, Badhaiyatal",
        "Province 5, Bardiya, Bansgadhi",
        "Province 5, Bardiya, Barbardiya",
        "Province 5, Bardiya, Bardiya National Park",
        "Province 5, Bardiya, Geruwa",
        "Province 5, Bardiya, Gulariya",
        "Province 5, Bardiya, Madhuban",
        "Province 5, Bardiya, Rajapur",
        "Province 5, Bardiya, Thakurbaba",
        "Province 6, Salyan, Agnisair Krishnasawaran",
        "Province 6, Salyan, Balanbihul",
        "Province 6, Salyan, Bishnupur",
        "Province 6, Salyan, Bodebarsain",
        "Province 6, Salyan, Chhinnamasta",
        "Province 6, Salyan, Dakneshwori",
        "Province 6, Salyan, Hanumannagar Kankalini",
        "Province 6, Salyan, Kanchanrup",
        "Province 6, Salyan, Khadak",
        "Province 6, Salyan, Koshi Tappu Wildlife Reserve",
        "Province 6, Salyan, Mahadeva",
        "Province 6, Salyan, Rajbiraj",
        "Province 6, Salyan, Rajgadh",
        "Province 6, Salyan, Rupani",
        "Province 6, Salyan, Saptakoshi",
        "Province 6, Salyan, Shambhunath",
        "Province 6, Salyan, Surunga",
        "Province 6, Salyan, Tilathi Koiladi",
        "Province 6, Salyan, Tirahut",
        "Province 6, Rukum West, Bagchaur",
        "Province 6, Rukum West, Bangad Kupinde",
        "Province 6, Rukum West, Chhatreshwori",
        "Province 6, Rukum West, Darma",
        "Province 6, Rukum West, Kalimati",
        "Province 6, Rukum West, Kapurkot",
        "Province 6, Rukum West, Kumakh",
        "Province 6, Rukum West, Sharada",
        "Province 6, Rukum West, Siddhakumakh",
        "Province 6, Rukum West, Triveni",
        "Province 6, Surkhet, Aanbukhaireni",
        "Province 6, Surkhet, Bandipur",
        "Province 6, Surkhet, Bhanu",
        "Province 6, Surkhet, Bhimad",
        "Province 6, Surkhet, Byas",
        "Province 6, Surkhet, Devghat",
        "Province 6, Surkhet, Ghiring",
        "Province 6, Surkhet, Myagde",
        "Province 6, Surkhet, Rishing",
        "Province 6, Surkhet, Shuklagandaki",
        "Province 6, Kalikot, Khandachakra",
        "Province 6, Kalikot, Mahawai",
        "Province 6, Kalikot, Naraharinath",
        "Province 6, Kalikot, Pachaljharna",
        "Province 6, Kalikot, Palata",
        "Province 6, Kalikot, Raskot",
        "Province 6, Kalikot, Sanni Triveni",
        "Province 6, Kalikot, Shuvakalika",
        "Province 6, Kalikot, Tilagupha",
        "Province 6, Mugu, Chhayanath Rara",
        "Province 6, Mugu, Khatyad",
        "Province 6, Mugu, Mugum Karmarong",
        "Province 6, Mugu, Soru",
        "Province 6, Dailekh, Aathbis",
        "Province 6, Dailekh, Bhagawatimai",
        "Province 6, Dailekh, Bhairavi",
        "Province 6, Dailekh, Chamunda Bindrasaini",
        "Province 6, Dailekh, Dullu",
        "Province 6, Dailekh, Dungeshwor",
        "Province 6, Dailekh, Gurans",
        "Province 6, Dailekh, Mahabu",
        "Province 6, Dailekh, Narayan",
        "Province 6, Dailekh, Naumule",
        "Province 6, Dailekh, Thantikandh",
        "Province 6, Humla, Adanchuli",
        "Province 6, Humla, Chankheli",
        "Province 6, Humla, Kharpunath",
        "Province 6, Humla, Namkha",
        "Province 6, Humla, Sarkegad",
        "Province 6, Humla, Simkot",
        "Province 6, Humla, Tanjakot",
        "Province 6, Dolpa, Chharka Tangsong",
        "Province 6, Dolpa, Dolpobuddha",
        "Province 6, Dolpa, Jagadulla",
        "Province 6, Dolpa, Kaike",
        "Province 6, Dolpa, Mudkechula",
        "Province 6, Dolpa, Shey Phoksundo",
        "Province 6, Dolpa, Thulibheri",
        "Province 6, Dolpa, Tripurasundari",
        "Province 6, Jumla, Chandannath",
        "Province 6, Jumla, Guthichaur",
        "Province 6, Jumla, Hima",
        "Province 6, Jumla, Kanakasundari",
        "Province 6, Jumla, Patarasi",
        "Province 6, Jumla, Sinja",
        "Province 6, Jumla, Tatopani",
        "Province 6, Jumla, Tila",
        "Province 6, Jajarkot, Barekot",
        "Province 6, Jajarkot, Bheri",
        "Province 6, Jajarkot, Chhedagad",
        "Province 6, Jajarkot, Junichande",
        "Province 6, Jajarkot, Kushe",
        "Province 6, Jajarkot, Nalgad",
        "Province 6, Jajarkot, Shivalaya",
        "Province 7, Doti, Aadarsha",
        "Province 7, Doti, Badikedar",
        "Province 7, Doti, Bogatan Phudsil",
        "Province 7, Doti, Dipayal Silgadhi",
        "Province 7, Doti, Jorayal",
        "Province 7, Doti, K.I. Singh",
        "Province 7, Doti, Khaptad National Park",
        "Province 7, Doti, Purbichauki",
        "Province 7, Doti, Sayal",
        "Province 7, Doti, Shikhar",
        "Province 7, Achham, Bannigadhi Jayagadh",
        "Province 7, Achham, Chaurpati",
        "Province 7, Achham, Dhakari",
        "Province 7, Achham, Kamalbazar",
        "Province 7, Achham, Khaptad National Park",
        "Province 7, Achham, Mangalsen",
        "Province 7, Achham, Mellekh",
        "Province 7, Achham, Panchdeval Binayak",
        "Province 7, Achham, Ramaroshan",
        "Province 7, Achham, Sanphebagar",
        "Province 7, Achham, Turmakhand",
        "Province 7, Dadeldhura, Aalital",
        "Province 7, Dadeldhura, Ajayameru",
        "Province 7, Dadeldhura, Amargadhi",
        "Province 7, Dadeldhura, Bhageshwor",
        "Province 7, Dadeldhura, Ganyapdhura",
        "Province 7, Dadeldhura, Navadurga",
        "Province 7, Dadeldhura, Parashuram",
        "Province 7, Darchula, Apihimal",
        "Province 7, Darchula, Duhun",
        "Province 7, Darchula, Lekam",
        "Province 7, Darchula, Mahakali",
        "Province 7, Darchula, Malikarjun",
        "Province 7, Darchula, Marma",
        "Province 7, Darchula, Naugad",
        "Province 7, Darchula, Shailyashikhar",
        "Province 7, Darchula, Vyans",
        "Province 7, Baitadi, Dasharath Chand",
        "Province 7, Baitadi, Dilasaini",
        "Province 7, Baitadi, Dogadakedar",
        "Province 7, Baitadi, Melauli",
        "Province 7, Baitadi, Pancheshwor",
        "Province 7, Baitadi, Patan",
        "Province 7, Baitadi, Purchaudi",
        "Province 7, Baitadi, Shivanath",
        "Province 7, Baitadi, Sigas",
        "Province 7, Baitadi, Surnaya",
        "Province 7, Kanchanpur, Bedkot",
        "Province 7, Kanchanpur, Belauri",
        "Province 7, Kanchanpur, Beldandi",
        "Province 7, Kanchanpur, Bhimdatta",
        "Province 7, Kanchanpur, Krishnapur",
        "Province 7, Kanchanpur, Laljhadi",
        "Province 7, Kanchanpur, Mahakali",
        "Province 7, Kanchanpur, Punarbas",
        "Province 7, Kanchanpur, Shuklaphanta",
        "Province 7, Kanchanpur, Shuklaphanta National Park",
        "Province 7, Kailali, Bardgoriya",
        "Province 7, Kailali, Bhajani",
        "Province 7, Kailali, Chure",
        "Province 7, Kailali, Dhangadhi",
        "Province 7, Kailali, Gauriganga",
        "Province 7, Kailali, Ghodaghodi",
        "Province 7, Kailali, Godawari",
        "Province 7, Kailali, Janaki",
        "Province 7, Kailali, Joshipur",
        "Province 7, Kailali, Kailari",
        "Province 7, Kailali, Lamkichuha",
        "Province 7, Kailali, Mohanyal",
        "Province 7, Kailali, Tikapur",
        "Province 7, Bajhang, Bitthadchir",
        "Province 7, Bajhang, Bungal",
        "Province 7, Bajhang, Chhabis Pathibhera",
        "Province 7, Bajhang, Durgathali",
        "Province 7, Bajhang, Jayaprithvi",
        "Province 7, Bajhang, Kedarsyun",
        "Province 7, Bajhang, Khaptad National Park",
        "Province 7, Bajhang, Khaptadchhanna",
        "Province 7, Bajhang, Masta",
        "Province 7, Bajhang, Saipal",
        "Province 7, Bajhang, Surma",
        "Province 7, Bajhang, Talkot",
        "Province 7, Bajhang, Thalara",
        "Province 7, Bajura, Badimalika",
        "Province 7, Bajura, Budhiganga",
        "Province 7, Bajura, Budhinanda",
        "Province 7, Bajura, Gaumul",
        "Province 7, Bajura, Himali",
        "Province 7, Bajura, Jagannath",
        "Province 7, Bajura, Khaptad Chhededaha",
        "Province 7, Bajura, Khaptad National Park",
        "Province 7, Bajura, Swamikartik Khapar",
        "Province 7, Bajura, Triveni"
        ]
    
}

const reducer =(state=initialstate,action) => {
    switch(action.type){
        case 'Update_Lan':
            let newstate = state;
            newstate.lan = action.data;
            return newstate;
            

        default:
            return state;

    }
}

export default combineReducers({
    reducer,
    checkSymptom: checkSymptomReducer,
  
});
